import type { Metadata } from "next";
import "./globals.css";
import { Geologica } from "next/font/google";
import MobileWarning from "./MobileWarning";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const geologica = Geologica({
  subsets: ['latin'],
  weight: ['400', '600', '700', '800'], // Specify the desired weight'
  variable: '--font-geologica',
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geologica.className} antialiased`}
      >
         <MobileWarning />
        {children}
      </body>
    </html>
  );
}
