import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Geologica, Poppins, Roboto } from "next/font/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const roboto = Roboto({
  subsets: ['latin'],
  weight: '700', // Specify the desired weight
});

const geologica = Geologica({
  subsets: ['latin'],
  weight: ['400', '600', '700', '800'], // Specify the desired weight'
  variable: '--font-geologica',
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${geologica.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
